name: assignment19
channels:
  - conda-forge
  - defaults
dependencies:
  - nbconvert=6.4.5
  - python=3.10.2
  - ipython=8.1.1
  - numpy=1.22.2
  - scipy=1.8.0
  - matplotlib=3.5.1
  - pandas=1.4.1
  - pyyaml=6.0
